# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/astro_seb/Github/Onstep_Generator/configurator.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_configurator(object):
    def setupUi(self, configurator):
        configurator.setObjectName("configurator")
        configurator.resize(654, 781)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("OnStep_Logo_Medium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        configurator.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(configurator)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("OnStep_Logo_Medium.png"))
        self.label_15.setScaledContents(False)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.general_tab = QtWidgets.QWidget()
        self.general_tab.setObjectName("general_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.general_tab)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.general_tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.board_combo = QtWidgets.QComboBox(self.general_tab)
        self.board_combo.setObjectName("board_combo")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.board_combo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.general_tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.mount_combo = QtWidgets.QComboBox(self.general_tab)
        self.mount_combo.setObjectName("mount_combo")
        self.mount_combo.addItem("")
        self.mount_combo.addItem("")
        self.mount_combo.addItem("")
        self.horizontalLayout.addWidget(self.mount_combo)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.general_tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.maxrate_spin = QtWidgets.QSpinBox(self.general_tab)
        self.maxrate_spin.setMaximum(256)
        self.maxrate_spin.setProperty("value", 96)
        self.maxrate_spin.setObjectName("maxrate_spin")
        self.horizontalLayout_3.addWidget(self.maxrate_spin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.general_tab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.auto_side_combo = QtWidgets.QComboBox(self.general_tab)
        self.auto_side_combo.setObjectName("auto_side_combo")
        self.auto_side_combo.addItem("")
        self.auto_side_combo.addItem("")
        self.horizontalLayout_5.addWidget(self.auto_side_combo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.axis2_mod_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis2_mod_combo.setObjectName("axis2_mod_combo")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.gridLayout.addWidget(self.axis2_mod_combo, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.general_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.axis1_mod_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis1_mod_combo.setObjectName("axis1_mod_combo")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.gridLayout.addWidget(self.axis1_mod_combo, 5, 1, 1, 1)
        self.axis2_motor_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis2_motor_combo.setObjectName("axis2_motor_combo")
        self.axis2_motor_combo.addItem("")
        self.axis2_motor_combo.addItem("")
        self.axis2_motor_combo.addItem("")
        self.gridLayout.addWidget(self.axis2_motor_combo, 3, 2, 1, 1)
        self.axis1_driver_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis1_driver_combo.setObjectName("axis1_driver_combo")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.gridLayout.addWidget(self.axis1_driver_combo, 6, 1, 1, 1)
        self.axis1_gear_spindouble = QtWidgets.QDoubleSpinBox(self.general_tab)
        self.axis1_gear_spindouble.setDecimals(3)
        self.axis1_gear_spindouble.setMinimum(1.0)
        self.axis1_gear_spindouble.setMaximum(99999.99)
        self.axis1_gear_spindouble.setObjectName("axis1_gear_spindouble")
        self.gridLayout.addWidget(self.axis1_gear_spindouble, 2, 1, 1, 1)
        self.axis1_worm_spindouble = QtWidgets.QDoubleSpinBox(self.general_tab)
        self.axis1_worm_spindouble.setDecimals(3)
        self.axis1_worm_spindouble.setMinimum(1.0)
        self.axis1_worm_spindouble.setMaximum(99999.99)
        self.axis1_worm_spindouble.setProperty("value", 144.0)
        self.axis1_worm_spindouble.setObjectName("axis1_worm_spindouble")
        self.gridLayout.addWidget(self.axis1_worm_spindouble, 1, 1, 1, 1)
        self.axis2_driver_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis2_driver_combo.setObjectName("axis2_driver_combo")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.gridLayout.addWidget(self.axis2_driver_combo, 6, 2, 1, 1)
        self.axis2_worm_spindouble = QtWidgets.QDoubleSpinBox(self.general_tab)
        self.axis2_worm_spindouble.setDecimals(3)
        self.axis2_worm_spindouble.setMinimum(1.0)
        self.axis2_worm_spindouble.setMaximum(99999.99)
        self.axis2_worm_spindouble.setProperty("value", 144.0)
        self.axis2_worm_spindouble.setObjectName("axis2_worm_spindouble")
        self.gridLayout.addWidget(self.axis2_worm_spindouble, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.general_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.axis1_reverse_checkBox = QtWidgets.QCheckBox(self.general_tab)
        self.axis1_reverse_checkBox.setText("")
        self.axis1_reverse_checkBox.setObjectName("axis1_reverse_checkBox")
        self.gridLayout.addWidget(self.axis1_reverse_checkBox, 7, 1, 1, 1)
        self.axis2_gear_spindouble = QtWidgets.QDoubleSpinBox(self.general_tab)
        self.axis2_gear_spindouble.setDecimals(3)
        self.axis2_gear_spindouble.setMinimum(1.0)
        self.axis2_gear_spindouble.setMaximum(99999.99)
        self.axis2_gear_spindouble.setProperty("value", 1.0)
        self.axis2_gear_spindouble.setObjectName("axis2_gear_spindouble")
        self.gridLayout.addWidget(self.axis2_gear_spindouble, 2, 2, 1, 1)
        self.axis1_motor_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis1_motor_combo.setObjectName("axis1_motor_combo")
        self.axis1_motor_combo.addItem("")
        self.axis1_motor_combo.addItem("")
        self.axis1_motor_combo.addItem("")
        self.gridLayout.addWidget(self.axis1_motor_combo, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.general_tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.axis2_micro_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis2_micro_combo.setObjectName("axis2_micro_combo")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.gridLayout.addWidget(self.axis2_micro_combo, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.general_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.axis1_micro_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis1_micro_combo.setObjectName("axis1_micro_combo")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.gridLayout.addWidget(self.axis1_micro_combo, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.general_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.general_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.general_tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.general_tab)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 7, 0, 1, 1)
        self.axis2_reverse_checkBox = QtWidgets.QCheckBox(self.general_tab)
        self.axis2_reverse_checkBox.setText("")
        self.axis2_reverse_checkBox.setObjectName("axis2_reverse_checkBox")
        self.gridLayout.addWidget(self.axis2_reverse_checkBox, 7, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.general_tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.axis1_enable_comboBox = QtWidgets.QComboBox(self.general_tab)
        self.axis1_enable_comboBox.setObjectName("axis1_enable_comboBox")
        self.axis1_enable_comboBox.addItem("")
        self.axis1_enable_comboBox.addItem("")
        self.gridLayout.addWidget(self.axis1_enable_comboBox, 8, 1, 1, 1)
        self.axis2_enable_comboBox = QtWidgets.QComboBox(self.general_tab)
        self.axis2_enable_comboBox.setObjectName("axis2_enable_comboBox")
        self.axis2_enable_comboBox.addItem("")
        self.axis2_enable_comboBox.addItem("")
        self.gridLayout.addWidget(self.axis2_enable_comboBox, 8, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.general_tab)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 8, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.general_tab)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 9, 0, 1, 1)
        self.axis1_fault_comboBox = QtWidgets.QComboBox(self.general_tab)
        self.axis1_fault_comboBox.setObjectName("axis1_fault_comboBox")
        self.axis1_fault_comboBox.addItem("")
        self.axis1_fault_comboBox.addItem("")
        self.axis1_fault_comboBox.addItem("")
        self.gridLayout.addWidget(self.axis1_fault_comboBox, 9, 1, 1, 1)
        self.axis2_fault_comboBox = QtWidgets.QComboBox(self.general_tab)
        self.axis2_fault_comboBox.setObjectName("axis2_fault_comboBox")
        self.axis2_fault_comboBox.addItem("")
        self.axis2_fault_comboBox.addItem("")
        self.axis2_fault_comboBox.addItem("")
        self.gridLayout.addWidget(self.axis2_fault_comboBox, 9, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.general_tab, "")
        self.axis3_2_tab = QtWidgets.QWidget()
        self.axis3_2_tab.setObjectName("axis3_2_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.axis3_2_tab)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_35 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 8, 0, 1, 1)
        self.rot_max_angle_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.rot_max_angle_doubleSpinBox.setEnabled(False)
        self.rot_max_angle_doubleSpinBox.setMinimum(-180.0)
        self.rot_max_angle_doubleSpinBox.setMaximum(180.0)
        self.rot_max_angle_doubleSpinBox.setProperty("value", 180.0)
        self.rot_max_angle_doubleSpinBox.setObjectName("rot_max_angle_doubleSpinBox")
        self.gridLayout_3.addWidget(self.rot_max_angle_doubleSpinBox, 8, 1, 1, 1)
        self.rot_mrate_spinBox = QtWidgets.QSpinBox(self.axis3_2_tab)
        self.rot_mrate_spinBox.setEnabled(False)
        self.rot_mrate_spinBox.setMaximum(256)
        self.rot_mrate_spinBox.setProperty("value", 8)
        self.rot_mrate_spinBox.setObjectName("rot_mrate_spinBox")
        self.gridLayout_3.addWidget(self.rot_mrate_spinBox, 1, 1, 1, 1)
        self.focus1_min_mil_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.focus1_min_mil_doubleSpinBox.setEnabled(False)
        self.focus1_min_mil_doubleSpinBox.setMinimum(-999999.99)
        self.focus1_min_mil_doubleSpinBox.setMaximum(999999.99)
        self.focus1_min_mil_doubleSpinBox.setProperty("value", -25.0)
        self.focus1_min_mil_doubleSpinBox.setObjectName("focus1_min_mil_doubleSpinBox")
        self.gridLayout_3.addWidget(self.focus1_min_mil_doubleSpinBox, 7, 2, 1, 1)
        self.focus2_mrate_spinBox = QtWidgets.QSpinBox(self.axis3_2_tab)
        self.focus2_mrate_spinBox.setEnabled(False)
        self.focus2_mrate_spinBox.setMaximum(256)
        self.focus2_mrate_spinBox.setProperty("value", 8)
        self.focus2_mrate_spinBox.setObjectName("focus2_mrate_spinBox")
        self.gridLayout_3.addWidget(self.focus2_mrate_spinBox, 1, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 4, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_37 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_7.addWidget(self.label_37)
        self.label_42 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_7.addWidget(self.label_42)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 5, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 6, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_40.setObjectName("label_40")
        self.gridLayout_3.addWidget(self.label_40, 7, 0, 1, 1)
        self.focus1_micro_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.focus1_micro_doubleSpinBox.setEnabled(False)
        self.focus1_micro_doubleSpinBox.setMaximum(999999.99)
        self.focus1_micro_doubleSpinBox.setProperty("value", 0.5)
        self.focus1_micro_doubleSpinBox.setObjectName("focus1_micro_doubleSpinBox")
        self.gridLayout_3.addWidget(self.focus1_micro_doubleSpinBox, 5, 2, 1, 1)
        self.focus2_checkBox = QtWidgets.QCheckBox(self.axis3_2_tab)
        self.focus2_checkBox.setObjectName("focus2_checkBox")
        self.gridLayout_3.addWidget(self.focus2_checkBox, 0, 3, 1, 1)
        self.rot_reverse_checkBox = QtWidgets.QCheckBox(self.axis3_2_tab)
        self.rot_reverse_checkBox.setEnabled(False)
        self.rot_reverse_checkBox.setText("")
        self.rot_reverse_checkBox.setObjectName("rot_reverse_checkBox")
        self.gridLayout_3.addWidget(self.rot_reverse_checkBox, 6, 1, 1, 1)
        self.focus2_max_mil_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.focus2_max_mil_doubleSpinBox.setEnabled(False)
        self.focus2_max_mil_doubleSpinBox.setMinimum(-999999.0)
        self.focus2_max_mil_doubleSpinBox.setMaximum(999999.99)
        self.focus2_max_mil_doubleSpinBox.setProperty("value", 25.0)
        self.focus2_max_mil_doubleSpinBox.setObjectName("focus2_max_mil_doubleSpinBox")
        self.gridLayout_3.addWidget(self.focus2_max_mil_doubleSpinBox, 8, 3, 1, 1)
        self.focus1_checkBox = QtWidgets.QCheckBox(self.axis3_2_tab)
        self.focus1_checkBox.setObjectName("focus1_checkBox")
        self.gridLayout_3.addWidget(self.focus1_checkBox, 0, 2, 1, 1)
        self.rot_step_comboBox = QtWidgets.QComboBox(self.axis3_2_tab)
        self.rot_step_comboBox.setEnabled(False)
        self.rot_step_comboBox.setObjectName("rot_step_comboBox")
        self.gridLayout_3.addWidget(self.rot_step_comboBox, 2, 1, 1, 1)
        self.rot_checkBox = QtWidgets.QCheckBox(self.axis3_2_tab)
        self.rot_checkBox.setObjectName("rot_checkBox")
        self.gridLayout_3.addWidget(self.rot_checkBox, 0, 1, 1, 1)
        self.focus2_reverse_checkBox = QtWidgets.QCheckBox(self.axis3_2_tab)
        self.focus2_reverse_checkBox.setEnabled(False)
        self.focus2_reverse_checkBox.setText("")
        self.focus2_reverse_checkBox.setObjectName("focus2_reverse_checkBox")
        self.gridLayout_3.addWidget(self.focus2_reverse_checkBox, 6, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 1, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 3, 0, 1, 1)
        self.focus2_micro_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.focus2_micro_doubleSpinBox.setEnabled(False)
        self.focus2_micro_doubleSpinBox.setMaximum(999999.99)
        self.focus2_micro_doubleSpinBox.setProperty("value", 0.5)
        self.focus2_micro_doubleSpinBox.setObjectName("focus2_micro_doubleSpinBox")
        self.gridLayout_3.addWidget(self.focus2_micro_doubleSpinBox, 5, 3, 1, 1)
        self.focus1_max_mil_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.focus1_max_mil_doubleSpinBox.setEnabled(False)
        self.focus1_max_mil_doubleSpinBox.setMinimum(-999999.99)
        self.focus1_max_mil_doubleSpinBox.setMaximum(999999.99)
        self.focus1_max_mil_doubleSpinBox.setProperty("value", 25.0)
        self.focus1_max_mil_doubleSpinBox.setObjectName("focus1_max_mil_doubleSpinBox")
        self.gridLayout_3.addWidget(self.focus1_max_mil_doubleSpinBox, 8, 2, 1, 1)
        self.rot_min_angle_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.rot_min_angle_doubleSpinBox.setEnabled(False)
        self.rot_min_angle_doubleSpinBox.setMinimum(-180.0)
        self.rot_min_angle_doubleSpinBox.setMaximum(180.0)
        self.rot_min_angle_doubleSpinBox.setProperty("value", -180.0)
        self.rot_min_angle_doubleSpinBox.setObjectName("rot_min_angle_doubleSpinBox")
        self.gridLayout_3.addWidget(self.rot_min_angle_doubleSpinBox, 7, 1, 1, 1)
        self.rot_gear2_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.rot_gear2_doubleSpinBox.setEnabled(False)
        self.rot_gear2_doubleSpinBox.setMaximum(999999.99)
        self.rot_gear2_doubleSpinBox.setObjectName("rot_gear2_doubleSpinBox")
        self.gridLayout_3.addWidget(self.rot_gear2_doubleSpinBox, 5, 1, 1, 1)
        self.focus1_mrate_spinBox = QtWidgets.QSpinBox(self.axis3_2_tab)
        self.focus1_mrate_spinBox.setEnabled(False)
        self.focus1_mrate_spinBox.setMaximum(256)
        self.focus1_mrate_spinBox.setProperty("value", 8)
        self.focus1_mrate_spinBox.setObjectName("focus1_mrate_spinBox")
        self.gridLayout_3.addWidget(self.focus1_mrate_spinBox, 1, 2, 1, 1)
        self.focus1_reverse_checkBox = QtWidgets.QCheckBox(self.axis3_2_tab)
        self.focus1_reverse_checkBox.setEnabled(False)
        self.focus1_reverse_checkBox.setText("")
        self.focus1_reverse_checkBox.setObjectName("focus1_reverse_checkBox")
        self.gridLayout_3.addWidget(self.focus1_reverse_checkBox, 6, 2, 1, 1)
        self.rot_mode_comboBox = QtWidgets.QComboBox(self.axis3_2_tab)
        self.rot_mode_comboBox.setEnabled(False)
        self.rot_mode_comboBox.setObjectName("rot_mode_comboBox")
        self.rot_mode_comboBox.addItem("")
        self.rot_mode_comboBox.addItem("")
        self.rot_mode_comboBox.addItem("")
        self.rot_mode_comboBox.addItem("")
        self.rot_mode_comboBox.addItem("")
        self.rot_mode_comboBox.addItem("")
        self.rot_mode_comboBox.addItem("")
        self.rot_mode_comboBox.addItem("")
        self.rot_mode_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.rot_mode_comboBox, 3, 1, 1, 1)
        self.focus2_min_mil_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.focus2_min_mil_doubleSpinBox.setEnabled(False)
        self.focus2_min_mil_doubleSpinBox.setMinimum(-999999.99)
        self.focus2_min_mil_doubleSpinBox.setMaximum(999999.99)
        self.focus2_min_mil_doubleSpinBox.setProperty("value", -25.0)
        self.focus2_min_mil_doubleSpinBox.setObjectName("focus2_min_mil_doubleSpinBox")
        self.gridLayout_3.addWidget(self.focus2_min_mil_doubleSpinBox, 7, 3, 1, 1)
        self.rot_gear1_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.rot_gear1_doubleSpinBox.setEnabled(False)
        self.rot_gear1_doubleSpinBox.setMaximum(999999.99)
        self.rot_gear1_doubleSpinBox.setObjectName("rot_gear1_doubleSpinBox")
        self.gridLayout_3.addWidget(self.rot_gear1_doubleSpinBox, 4, 1, 1, 1)
        self.tabWidget.addTab(self.axis3_2_tab, "")
        self.option_tab = QtWidgets.QWidget()
        self.option_tab.setObjectName("option_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.option_tab)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(self.option_tab)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 596, 857))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        self.serial_baud_comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.serial_baud_comboBox.setObjectName("serial_baud_comboBox")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.serial_baud_comboBox.addItem("")
        self.horizontalLayout_13.addWidget(self.serial_baud_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pec_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.pec_checkBox.setObjectName("pec_checkBox")
        self.horizontalLayout_4.addWidget(self.pec_checkBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setEnabled(False)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.pec_buffer_spin = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.pec_buffer_spin.setEnabled(False)
        self.pec_buffer_spin.setMaximum(100000)
        self.pec_buffer_spin.setProperty("value", 824)
        self.pec_buffer_spin.setObjectName("pec_buffer_spin")
        self.horizontalLayout_4.addWidget(self.pec_buffer_spin)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.goto_assist_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.goto_assist_checkBox.setObjectName("goto_assist_checkBox")
        self.verticalLayout_3.addWidget(self.goto_assist_checkBox)
        self.strict_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.strict_checkBox.setObjectName("strict_checkBox")
        self.verticalLayout_3.addWidget(self.strict_checkBox)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.st4_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.st4_checkBox.setObjectName("st4_checkBox")
        self.horizontalLayout_8.addWidget(self.st4_checkBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.alternative_st4_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.alternative_st4_checkBox.setEnabled(False)
        self.alternative_st4_checkBox.setObjectName("alternative_st4_checkBox")
        self.horizontalLayout_8.addWidget(self.alternative_st4_checkBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.hand_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.hand_checkBox.setEnabled(False)
        self.hand_checkBox.setObjectName("hand_checkBox")
        self.horizontalLayout_8.addWidget(self.hand_checkBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.separate_pulse_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.separate_pulse_checkBox.setChecked(True)
        self.separate_pulse_checkBox.setObjectName("separate_pulse_checkBox")
        self.verticalLayout_3.addWidget(self.separate_pulse_checkBox)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.guide_time_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.guide_time_spinBox.setMaximum(86400)
        self.guide_time_spinBox.setObjectName("guide_time_spinBox")
        self.horizontalLayout_14.addWidget(self.guide_time_spinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.rtc_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.rtc_checkBox.setObjectName("rtc_checkBox")
        self.horizontalLayout_9.addWidget(self.rtc_checkBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.rtc_time_comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.rtc_time_comboBox.setEnabled(False)
        self.rtc_time_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.rtc_time_comboBox.setObjectName("rtc_time_comboBox")
        self.rtc_time_comboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.rtc_time_comboBox)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.pps_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.pps_checkBox.setObjectName("pps_checkBox")
        self.verticalLayout_3.addWidget(self.pps_checkBox)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pec_set_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.pec_set_checkBox.setObjectName("pec_set_checkBox")
        self.horizontalLayout_10.addWidget(self.pec_set_checkBox)
        self.analog_pec_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.analog_pec_spinBox.setEnabled(False)
        self.analog_pec_spinBox.setMaximum(1023)
        self.analog_pec_spinBox.setProperty("value", 1023)
        self.analog_pec_spinBox.setObjectName("analog_pec_spinBox")
        self.horizontalLayout_10.addWidget(self.analog_pec_spinBox)
        self.pec_logic_comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.pec_logic_comboBox.setEnabled(False)
        self.pec_logic_comboBox.setObjectName("pec_logic_comboBox")
        self.pec_logic_comboBox.addItem("")
        self.pec_logic_comboBox.addItem("")
        self.horizontalLayout_10.addWidget(self.pec_logic_comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.limit_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.limit_checkBox.setObjectName("limit_checkBox")
        self.verticalLayout_3.addWidget(self.limit_checkBox)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.led_state_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.led_state_checkBox.setObjectName("led_state_checkBox")
        self.horizontalLayout_11.addWidget(self.led_state_checkBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.reticule_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.reticule_checkBox.setEnabled(False)
        self.reticule_checkBox.setObjectName("reticule_checkBox")
        self.horizontalLayout_11.addWidget(self.reticule_checkBox)
        self.intensity_led_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.intensity_led_spinBox.setEnabled(False)
        self.intensity_led_spinBox.setMaximum(255)
        self.intensity_led_spinBox.setProperty("value", 255)
        self.intensity_led_spinBox.setObjectName("intensity_led_spinBox")
        self.horizontalLayout_11.addWidget(self.intensity_led_spinBox)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.state_led2_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.state_led2_checkBox.setObjectName("state_led2_checkBox")
        self.verticalLayout_3.addWidget(self.state_led2_checkBox)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.buzzer_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.buzzer_checkBox.setObjectName("buzzer_checkBox")
        self.horizontalLayout_12.addWidget(self.buzzer_checkBox)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setEnabled(False)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.freq_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.freq_spinBox.setEnabled(False)
        self.freq_spinBox.setMaximum(30000)
        self.freq_spinBox.setProperty("value", 2000)
        self.freq_spinBox.setObjectName("freq_spinBox")
        self.horizontalLayout_12.addWidget(self.freq_spinBox)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.default_sound_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.default_sound_checkBox.setEnabled(False)
        self.default_sound_checkBox.setChecked(True)
        self.default_sound_checkBox.setObjectName("default_sound_checkBox")
        self.horizontalLayout_12.addWidget(self.default_sound_checkBox)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.atmos_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.atmos_checkBox.setObjectName("atmos_checkBox")
        self.verticalLayout_3.addWidget(self.atmos_checkBox)
        self.home_pause_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.home_pause_checkBox.setObjectName("home_pause_checkBox")
        self.verticalLayout_3.addWidget(self.home_pause_checkBox)
        self.max_rate_save_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.max_rate_save_checkBox.setObjectName("max_rate_save_checkBox")
        self.verticalLayout_3.addWidget(self.max_rate_save_checkBox)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_17.addWidget(self.label_22)
        self.degre_accel_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.degre_accel_doubleSpinBox.setDecimals(1)
        self.degre_accel_doubleSpinBox.setMinimum(1.0)
        self.degre_accel_doubleSpinBox.setSingleStep(1.0)
        self.degre_accel_doubleSpinBox.setProperty("value", 5.0)
        self.degre_accel_doubleSpinBox.setObjectName("degre_accel_doubleSpinBox")
        self.horizontalLayout_17.addWidget(self.degre_accel_doubleSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_16.addWidget(self.label_23)
        self.degre_rapid_stop_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.degre_rapid_stop_doubleSpinBox.setDecimals(1)
        self.degre_rapid_stop_doubleSpinBox.setMinimum(1.0)
        self.degre_rapid_stop_doubleSpinBox.setProperty("value", 1.0)
        self.degre_rapid_stop_doubleSpinBox.setObjectName("degre_rapid_stop_doubleSpinBox")
        self.horizontalLayout_16.addWidget(self.degre_rapid_stop_doubleSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_15.addWidget(self.label_24)
        self.backlash_rate_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.backlash_rate_spinBox.setProperty("value", 25)
        self.backlash_rate_spinBox.setObjectName("backlash_rate_spinBox")
        self.horizontalLayout_15.addWidget(self.backlash_rate_spinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.off_axis2_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.off_axis2_checkBox.setObjectName("off_axis2_checkBox")
        self.verticalLayout_3.addWidget(self.off_axis2_checkBox)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_18.addWidget(self.label_28)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem12)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_18.addWidget(self.label_43)
        self.degre_e_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.degre_e_spinBox.setMinimum(-360)
        self.degre_e_spinBox.setMaximum(360)
        self.degre_e_spinBox.setProperty("value", 30)
        self.degre_e_spinBox.setObjectName("degre_e_spinBox")
        self.horizontalLayout_18.addWidget(self.degre_e_spinBox)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem13)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_18.addWidget(self.label_29)
        self.degre_w_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.degre_w_spinBox.setMinimum(-360)
        self.degre_w_spinBox.setMaximum(360)
        self.degre_w_spinBox.setProperty("value", 30)
        self.degre_w_spinBox.setObjectName("degre_w_spinBox")
        self.horizontalLayout_18.addWidget(self.degre_w_spinBox)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_19.addWidget(self.label_30)
        self.min_dec_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.min_dec_spinBox.setMinimum(-91)
        self.min_dec_spinBox.setMaximum(90)
        self.min_dec_spinBox.setProperty("value", -91)
        self.min_dec_spinBox.setObjectName("min_dec_spinBox")
        self.horizontalLayout_19.addWidget(self.min_dec_spinBox)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_19.addWidget(self.label_31)
        self.max_dec_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.max_dec_spinBox.setMinimum(-91)
        self.max_dec_spinBox.setMaximum(91)
        self.max_dec_spinBox.setProperty("value", 91)
        self.max_dec_spinBox.setObjectName("max_dec_spinBox")
        self.horizontalLayout_19.addWidget(self.max_dec_spinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_20.addWidget(self.label_32)
        self.pol_limit_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.pol_limit_spinBox.setMinimum(10)
        self.pol_limit_spinBox.setMaximum(12)
        self.pol_limit_spinBox.setProperty("value", 12)
        self.pol_limit_spinBox.setObjectName("pol_limit_spinBox")
        self.horizontalLayout_20.addWidget(self.pol_limit_spinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_21.addWidget(self.label_33)
        self.max_az_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.max_az_spinBox.setMinimum(180)
        self.max_az_spinBox.setMaximum(360)
        self.max_az_spinBox.setProperty("value", 180)
        self.max_az_spinBox.setObjectName("max_az_spinBox")
        self.horizontalLayout_21.addWidget(self.max_az_spinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.option_tab, "")
        self.arduino_tab = QtWidgets.QWidget()
        self.arduino_tab.setObjectName("arduino_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.arduino_tab)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.arduino_tab)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.arduino_tab)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem15)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.build_pushButton = QtWidgets.QPushButton(self.arduino_tab)
        self.build_pushButton.setEnabled(False)
        self.build_pushButton.setObjectName("build_pushButton")
        self.horizontalLayout_7.addWidget(self.build_pushButton)
        self.upload_pushButton = QtWidgets.QPushButton(self.arduino_tab)
        self.upload_pushButton.setEnabled(False)
        self.upload_pushButton.setObjectName("upload_pushButton")
        self.horizontalLayout_7.addWidget(self.upload_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_10.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.arduino_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.generate_buttom = QtWidgets.QPushButton(self.centralWidget)
        self.generate_buttom.setObjectName("generate_buttom")
        self.verticalLayout.addWidget(self.generate_buttom)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.path_line = QtWidgets.QLineEdit(self.centralWidget)
        self.path_line.setObjectName("path_line")
        self.horizontalLayout_6.addWidget(self.path_line)
        self.path_button = QtWidgets.QToolButton(self.centralWidget)
        self.path_button.setObjectName("path_button")
        self.horizontalLayout_6.addWidget(self.path_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.prompt_textbrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.prompt_textbrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.prompt_textbrowser.setObjectName("prompt_textbrowser")
        self.verticalLayout.addWidget(self.prompt_textbrowser)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        configurator.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(configurator)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 654, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuOnStep_Configurator = QtWidgets.QMenu(self.menuBar)
        self.menuOnStep_Configurator.setObjectName("menuOnStep_Configurator")
        self.menuInfo = QtWidgets.QMenu(self.menuBar)
        self.menuInfo.setObjectName("menuInfo")
        configurator.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(configurator)
        self.actionSave.setCheckable(False)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(configurator)
        self.actionLoad.setCheckable(False)
        self.actionLoad.setObjectName("actionLoad")
        self.actionAbout = QtWidgets.QAction(configurator)
        self.actionAbout.setCheckable(False)
        self.actionAbout.setEnabled(True)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOnStep_Configurator.addAction(self.actionSave)
        self.menuOnStep_Configurator.addAction(self.actionLoad)
        self.menuInfo.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuOnStep_Configurator.menuAction())
        self.menuBar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(configurator)
        self.tabWidget.setCurrentIndex(2)
        self.serial_baud_comboBox.setCurrentIndex(10)
        self.buttonBox.clicked['QAbstractButton*'].connect(configurator.close)
        self.rtc_checkBox.clicked['bool'].connect(self.state_led2_checkBox.setDisabled)
        self.pec_checkBox.clicked['bool'].connect(self.pec_buffer_spin.setEnabled)
        self.st4_checkBox.clicked['bool'].connect(self.alternative_st4_checkBox.setEnabled)
        self.st4_checkBox.clicked['bool'].connect(self.hand_checkBox.setEnabled)
        self.pec_set_checkBox.clicked['bool'].connect(self.analog_pec_spinBox.setEnabled)
        self.pec_set_checkBox.clicked['bool'].connect(self.pec_logic_comboBox.setEnabled)
        self.led_state_checkBox.clicked['bool'].connect(self.reticule_checkBox.setEnabled)
        self.reticule_checkBox.clicked['bool'].connect(self.intensity_led_spinBox.setEnabled)
        self.rtc_checkBox.clicked['bool'].connect(self.rtc_time_comboBox.setEnabled)
        self.state_led2_checkBox.clicked['bool'].connect(self.rtc_checkBox.setDisabled)
        self.pec_checkBox.clicked['bool'].connect(self.label_9.setEnabled)
        self.buzzer_checkBox.clicked['bool'].connect(self.label_19.setEnabled)
        self.buzzer_checkBox.clicked['bool'].connect(self.freq_spinBox.setEnabled)
        self.buzzer_checkBox.clicked['bool'].connect(self.default_sound_checkBox.setEnabled)
        self.rot_checkBox.clicked['bool'].connect(self.rot_mrate_spinBox.setEnabled)
        self.rot_checkBox.clicked['bool'].connect(self.rot_step_comboBox.setEnabled)
        self.rot_checkBox.clicked['bool'].connect(self.rot_mode_comboBox.setEnabled)
        self.rot_checkBox.clicked['bool'].connect(self.rot_gear2_doubleSpinBox.setEnabled)
        self.rot_checkBox.clicked['bool'].connect(self.rot_gear1_doubleSpinBox.setEnabled)
        self.rot_checkBox.clicked['bool'].connect(self.rot_reverse_checkBox.setEnabled)
        self.rot_checkBox.clicked['bool'].connect(self.rot_min_angle_doubleSpinBox.setEnabled)
        self.rot_checkBox.clicked['bool'].connect(self.rot_max_angle_doubleSpinBox.setEnabled)
        self.focus1_checkBox.clicked['bool'].connect(self.focus1_mrate_spinBox.setEnabled)
        self.focus1_checkBox.clicked['bool'].connect(self.focus1_micro_doubleSpinBox.setEnabled)
        self.focus1_checkBox.clicked['bool'].connect(self.focus1_reverse_checkBox.setEnabled)
        self.focus1_checkBox.clicked['bool'].connect(self.focus1_min_mil_doubleSpinBox.setEnabled)
        self.focus1_checkBox.clicked['bool'].connect(self.focus1_max_mil_doubleSpinBox.setEnabled)
        self.focus2_checkBox.clicked['bool'].connect(self.focus2_mrate_spinBox.setEnabled)
        self.focus2_checkBox.clicked['bool'].connect(self.focus2_micro_doubleSpinBox.setEnabled)
        self.focus2_checkBox.clicked['bool'].connect(self.focus2_reverse_checkBox.setEnabled)
        self.focus2_checkBox.clicked['bool'].connect(self.focus2_min_mil_doubleSpinBox.setEnabled)
        self.focus2_checkBox.clicked['bool'].connect(self.focus2_max_mil_doubleSpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(configurator)

    def retranslateUi(self, configurator):
        _translate = QtCore.QCoreApplication.translate
        configurator.setWindowTitle(_translate("configurator", "configurator"))
        self.label_14.setText(_translate("configurator", "Configuration Parameters"))
        self.label_8.setText(_translate("configurator", "Board Type"))
        self.board_combo.setItemText(0, _translate("configurator", "RAMPS 1.4 or 1.5"))
        self.board_combo.setItemText(1, _translate("configurator", "MiniPCB (2 axis)"))
        self.board_combo.setItemText(2, _translate("configurator", "MaxPCB (4 axis)"))
        self.board_combo.setItemText(3, _translate("configurator", "STM32F1"))
        self.board_combo.setItemText(4, _translate("configurator", "TivaC"))
        self.board_combo.setItemText(5, _translate("configurator", "Classic"))
        self.board_combo.setItemText(6, _translate("configurator", "Mega2560 Alternate"))
        self.board_combo.setItemText(7, _translate("configurator", "Custom"))
        self.label_7.setText(_translate("configurator", "Mount Type"))
        self.mount_combo.setItemText(0, _translate("configurator", "Equatorial"))
        self.mount_combo.setItemText(1, _translate("configurator", "Alt-Azimuth"))
        self.mount_combo.setItemText(2, _translate("configurator", "Fork"))
        self.label_10.setText(_translate("configurator", "Max Rate Ratio"))
        self.label_13.setText(_translate("configurator", "Auto Sideral Traking mod"))
        self.auto_side_combo.setItemText(0, _translate("configurator", "OFF"))
        self.auto_side_combo.setItemText(1, _translate("configurator", "ON"))
        self.axis2_mod_combo.setItemText(0, _translate("configurator", "OFF"))
        self.axis2_mod_combo.setItemText(1, _translate("configurator", "1"))
        self.axis2_mod_combo.setItemText(2, _translate("configurator", "2"))
        self.axis2_mod_combo.setItemText(3, _translate("configurator", "4"))
        self.axis2_mod_combo.setItemText(4, _translate("configurator", "8"))
        self.axis2_mod_combo.setItemText(5, _translate("configurator", "16"))
        self.axis2_mod_combo.setItemText(6, _translate("configurator", "32"))
        self.axis2_mod_combo.setItemText(7, _translate("configurator", "64"))
        self.axis2_mod_combo.setItemText(8, _translate("configurator", "128"))
        self.axis2_mod_combo.setItemText(9, _translate("configurator", "256"))
        self.label_3.setText(_translate("configurator", "Worm Wheel Ratio"))
        self.axis1_mod_combo.setItemText(0, _translate("configurator", "OFF"))
        self.axis1_mod_combo.setItemText(1, _translate("configurator", "1"))
        self.axis1_mod_combo.setItemText(2, _translate("configurator", "2"))
        self.axis1_mod_combo.setItemText(3, _translate("configurator", "4"))
        self.axis1_mod_combo.setItemText(4, _translate("configurator", "8"))
        self.axis1_mod_combo.setItemText(5, _translate("configurator", "16"))
        self.axis1_mod_combo.setItemText(6, _translate("configurator", "32"))
        self.axis1_mod_combo.setItemText(7, _translate("configurator", "64"))
        self.axis1_mod_combo.setItemText(8, _translate("configurator", "128"))
        self.axis1_mod_combo.setItemText(9, _translate("configurator", "256"))
        self.axis2_motor_combo.setItemText(0, _translate("configurator", "200 steps, 1.8°/step"))
        self.axis2_motor_combo.setItemText(1, _translate("configurator", "400 steps, 0.9°/step"))
        self.axis2_motor_combo.setItemText(2, _translate("configurator", "48 steps, 7.5°/step"))
        self.axis1_driver_combo.setItemText(0, _translate("configurator", "A4988"))
        self.axis1_driver_combo.setItemText(1, _translate("configurator", "DRV8825"))
        self.axis1_driver_combo.setItemText(2, _translate("configurator", "LV8729 or RAPS128"))
        self.axis1_driver_combo.setItemText(3, _translate("configurator", "TMC2208"))
        self.axis1_driver_combo.setItemText(4, _translate("configurator", "TMC2130"))
        self.axis1_driver_combo.setItemText(5, _translate("configurator", "TMC2130 (Quiet)"))
        self.axis1_driver_combo.setItemText(6, _translate("configurator", "TMC2130 (VQuiet)"))
        self.axis1_driver_combo.setItemText(7, _translate("configurator", "TMC2130 (Quiet, LowPWR)"))
        self.axis1_driver_combo.setItemText(8, _translate("configurator", "TMC2130 (VQuiet, LowPWR)"))
        self.axis2_driver_combo.setItemText(0, _translate("configurator", "A4988"))
        self.axis2_driver_combo.setItemText(1, _translate("configurator", "DRV8825"))
        self.axis2_driver_combo.setItemText(2, _translate("configurator", "LV8729 or RAPS128"))
        self.axis2_driver_combo.setItemText(3, _translate("configurator", "TMC2208"))
        self.axis2_driver_combo.setItemText(4, _translate("configurator", "TMC2130"))
        self.axis2_driver_combo.setItemText(5, _translate("configurator", "TMC2130 (Quiet)"))
        self.axis2_driver_combo.setItemText(6, _translate("configurator", "TMC2130 (VQuiet)"))
        self.axis2_driver_combo.setItemText(7, _translate("configurator", "TMC2130 (Quiet, LowPWR)"))
        self.axis2_driver_combo.setItemText(8, _translate("configurator", "TMC2130 (VQuiet, LowPWR)"))
        self.label_4.setText(_translate("configurator", "Gears/Pulleys Ratio"))
        self.axis1_motor_combo.setItemText(0, _translate("configurator", "200 steps, 1.8°/step"))
        self.axis1_motor_combo.setItemText(1, _translate("configurator", "400 steps, 1.8°/step"))
        self.axis1_motor_combo.setItemText(2, _translate("configurator", "48 steps, 7.5°/step"))
        self.label.setText(_translate("configurator", "Axis 1"))
        self.axis2_micro_combo.setItemText(0, _translate("configurator", "1"))
        self.axis2_micro_combo.setItemText(1, _translate("configurator", "2"))
        self.axis2_micro_combo.setItemText(2, _translate("configurator", "4"))
        self.axis2_micro_combo.setItemText(3, _translate("configurator", "8"))
        self.axis2_micro_combo.setItemText(4, _translate("configurator", "16"))
        self.axis2_micro_combo.setItemText(5, _translate("configurator", "32"))
        self.axis2_micro_combo.setItemText(6, _translate("configurator", "64"))
        self.axis2_micro_combo.setItemText(7, _translate("configurator", "128"))
        self.axis2_micro_combo.setItemText(8, _translate("configurator", "256"))
        self.label_5.setText(_translate("configurator", "Stepper-Steps"))
        self.axis1_micro_combo.setItemText(0, _translate("configurator", "1"))
        self.axis1_micro_combo.setItemText(1, _translate("configurator", "2"))
        self.axis1_micro_combo.setItemText(2, _translate("configurator", "4"))
        self.axis1_micro_combo.setItemText(3, _translate("configurator", "8"))
        self.axis1_micro_combo.setItemText(4, _translate("configurator", "16"))
        self.axis1_micro_combo.setItemText(5, _translate("configurator", "32"))
        self.axis1_micro_combo.setItemText(6, _translate("configurator", "64"))
        self.axis1_micro_combo.setItemText(7, _translate("configurator", "128"))
        self.axis1_micro_combo.setItemText(8, _translate("configurator", "256"))
        self.label_6.setText(_translate("configurator", "MicroSteps Tracking"))
        self.label_2.setText(_translate("configurator", "Axis 2"))
        self.label_11.setText(_translate("configurator", "MicroSteps Slewing"))
        self.label_25.setText(_translate("configurator", "Reverse axis"))
        self.label_12.setText(_translate("configurator", "Driver Model"))
        self.axis1_enable_comboBox.setItemText(0, _translate("configurator", "HIGH"))
        self.axis1_enable_comboBox.setItemText(1, _translate("configurator", "LOW"))
        self.axis2_enable_comboBox.setItemText(0, _translate("configurator", "HIGH"))
        self.axis2_enable_comboBox.setItemText(1, _translate("configurator", "LOW"))
        self.label_26.setText(_translate("configurator", "Enable logic"))
        self.label_27.setText(_translate("configurator", "Fault Detection "))
        self.axis1_fault_comboBox.setItemText(0, _translate("configurator", "OFF"))
        self.axis1_fault_comboBox.setItemText(1, _translate("configurator", "HIGH"))
        self.axis1_fault_comboBox.setItemText(2, _translate("configurator", "LOW"))
        self.axis2_fault_comboBox.setItemText(0, _translate("configurator", "OFF"))
        self.axis2_fault_comboBox.setItemText(1, _translate("configurator", "HIGH"))
        self.axis2_fault_comboBox.setItemText(2, _translate("configurator", "LOW"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general_tab), _translate("configurator", "General"))
        self.label_35.setText(_translate("configurator", " Stepper Steps"))
        self.label_41.setText(_translate("configurator", " Max axis (degrees or millimeters)"))
        self.label_38.setText(_translate("configurator", " Gear 1 reduction Ratio"))
        self.label_37.setText(_translate("configurator", " Rotator : Gear 2 reduction Ratio"))
        self.label_42.setText(_translate("configurator", " Focuser : Step/MicroMeter"))
        self.label_39.setText(_translate("configurator", " Reverse Axis"))
        self.label_40.setText(_translate("configurator", " Min axis (degrees or millimeters)"))
        self.focus2_checkBox.setText(_translate("configurator", "Focuser 2"))
        self.focus1_checkBox.setText(_translate("configurator", "Focuser 1"))
        self.rot_checkBox.setText(_translate("configurator", "De-Rotator"))
        self.label_34.setText(_translate("configurator", " Max Rate Ratio"))
        self.label_36.setText(_translate("configurator", " Micro Steps"))
        self.rot_mode_comboBox.setItemText(0, _translate("configurator", "1"))
        self.rot_mode_comboBox.setItemText(1, _translate("configurator", "2"))
        self.rot_mode_comboBox.setItemText(2, _translate("configurator", "4"))
        self.rot_mode_comboBox.setItemText(3, _translate("configurator", "8"))
        self.rot_mode_comboBox.setItemText(4, _translate("configurator", "16"))
        self.rot_mode_comboBox.setItemText(5, _translate("configurator", "32"))
        self.rot_mode_comboBox.setItemText(6, _translate("configurator", "64"))
        self.rot_mode_comboBox.setItemText(7, _translate("configurator", "128"))
        self.rot_mode_comboBox.setItemText(8, _translate("configurator", "256"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.axis3_2_tab), _translate("configurator", "Axis3/2"))
        self.label_18.setText(_translate("configurator", "Tick for activate option :"))
        self.label_20.setText(_translate("configurator", "Serial 1 Baud (bit/s):"))
        self.serial_baud_comboBox.setItemText(0, _translate("configurator", "75"))
        self.serial_baud_comboBox.setItemText(1, _translate("configurator", "110"))
        self.serial_baud_comboBox.setItemText(2, _translate("configurator", "134.5"))
        self.serial_baud_comboBox.setItemText(3, _translate("configurator", "150"))
        self.serial_baud_comboBox.setItemText(4, _translate("configurator", "600"))
        self.serial_baud_comboBox.setItemText(5, _translate("configurator", "1200"))
        self.serial_baud_comboBox.setItemText(6, _translate("configurator", "1800"))
        self.serial_baud_comboBox.setItemText(7, _translate("configurator", "2400"))
        self.serial_baud_comboBox.setItemText(8, _translate("configurator", "4800"))
        self.serial_baud_comboBox.setItemText(9, _translate("configurator", "7200"))
        self.serial_baud_comboBox.setItemText(10, _translate("configurator", "9600"))
        self.serial_baud_comboBox.setItemText(11, _translate("configurator", "14400"))
        self.serial_baud_comboBox.setItemText(12, _translate("configurator", "19200"))
        self.serial_baud_comboBox.setItemText(13, _translate("configurator", "38400"))
        self.serial_baud_comboBox.setItemText(14, _translate("configurator", "56000"))
        self.serial_baud_comboBox.setItemText(15, _translate("configurator", "57600"))
        self.serial_baud_comboBox.setItemText(16, _translate("configurator", "115200"))
        self.serial_baud_comboBox.setItemText(17, _translate("configurator", "128000"))
        self.pec_checkBox.setText(_translate("configurator", "PEC"))
        self.label_9.setText(_translate("configurator", "PEC Buffer Size :"))
        self.goto_assist_checkBox.setText(_translate("configurator", "Align Goto Assist"))
        self.strict_checkBox.setText(_translate("configurator", "Strict Parking"))
        self.st4_checkBox.setText(_translate("configurator", "ST4"))
        self.alternative_st4_checkBox.setText(_translate("configurator", "Alternate Pins"))
        self.hand_checkBox.setText(_translate("configurator", "Hand Control"))
        self.separate_pulse_checkBox.setText(_translate("configurator", "Separate pulse guide rate"))
        self.label_21.setText(_translate("configurator", "Guide time Limit (seconds) :"))
        self.rtc_checkBox.setText(_translate("configurator", "RTC"))
        self.rtc_time_comboBox.setItemText(0, _translate("configurator", "RTC_DS3234"))
        self.pps_checkBox.setText(_translate("configurator", "PPS sensor"))
        self.pec_set_checkBox.setText(_translate("configurator", "PEC sensor ( 0 for digital)"))
        self.pec_logic_comboBox.setItemText(0, _translate("configurator", "HIGH"))
        self.pec_logic_comboBox.setItemText(1, _translate("configurator", "LOW"))
        self.limit_checkBox.setText(_translate("configurator", "Limit Sensor"))
        self.led_state_checkBox.setText(_translate("configurator", "Status LED"))
        self.reticule_checkBox.setText(_translate("configurator", "Reticule LED"))
        self.state_led2_checkBox.setText(_translate("configurator", "Status LED 2"))
        self.buzzer_checkBox.setText(_translate("configurator", "Buzzer"))
        self.label_19.setText(_translate("configurator", "Buzzer frequency (Hz) :"))
        self.default_sound_checkBox.setText(_translate("configurator", "Default Sound"))
        self.atmos_checkBox.setText(_translate("configurator", "Traking compensation for atmospheric refaction"))
        self.home_pause_checkBox.setText(_translate("configurator", "Home Pause"))
        self.max_rate_save_checkBox.setText(_translate("configurator", "Remember Max Rate"))
        self.label_22.setText(_translate("configurator", "Degrees for Acceleration :"))
        self.label_23.setText(_translate("configurator", "Degrees for Rapid Stop :"))
        self.label_24.setText(_translate("configurator", "Backlash Take up Rate :"))
        self.off_axis2_checkBox.setText(_translate("configurator", "Auto Power Off Axis 2"))
        self.label_28.setText(_translate("configurator", "Minute Past Meridian :"))
        self.label_43.setText(_translate("configurator", "E"))
        self.label_29.setText(_translate("configurator", "W"))
        self.label_30.setText(_translate("configurator", "Minimum DEC"))
        self.label_31.setText(_translate("configurator", "Maximum DEC"))
        self.label_32.setText(_translate("configurator", "Under Pole Limit (hours)"))
        self.label_33.setText(_translate("configurator", "Max Azimuth (degrees)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.option_tab), _translate("configurator", "Option"))
        self.label_17.setText(_translate("configurator", "This Tab is dedicated to generate and upload the OnStep code in the board"))
        self.label_16.setText(_translate("configurator", "Coming Soon !!!"))
        self.build_pushButton.setText(_translate("configurator", "Build"))
        self.upload_pushButton.setText(_translate("configurator", "Upload"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.arduino_tab), _translate("configurator", "Compile and Upload"))
        self.generate_buttom.setText(_translate("configurator", "Generate"))
        self.path_button.setText(_translate("configurator", "..."))
        self.prompt_textbrowser.setHtml(_translate("configurator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Configure your setup for Onstep !</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Standby...</p></body></html>"))
        self.menuOnStep_Configurator.setTitle(_translate("configurator", "File"))
        self.menuInfo.setTitle(_translate("configurator", "Info"))
        self.actionSave.setText(_translate("configurator", "Save"))
        self.actionSave.setShortcut(_translate("configurator", "Ctrl+S"))
        self.actionLoad.setText(_translate("configurator", "Load"))
        self.actionLoad.setShortcut(_translate("configurator", "Ctrl+O"))
        self.actionAbout.setText(_translate("configurator", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    configurator = QtWidgets.QMainWindow()
    ui = Ui_configurator()
    ui.setupUi(configurator)
    configurator.show()
    sys.exit(app.exec_())

