# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/developpeur/github/Onstep_Generator/configurator.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_configurator(object):
    def setupUi(self, configurator):
        configurator.setObjectName("configurator")
        configurator.resize(800, 781)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("OnStep_Logo_Medium.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        configurator.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(configurator)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("OnStep_Logo_Medium.png"))
        self.label_15.setScaledContents(False)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily("Waree")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.general_tab = QtWidgets.QWidget()
        self.general_tab.setObjectName("general_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.general_tab)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.general_tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.board_combo = QtWidgets.QComboBox(self.general_tab)
        self.board_combo.setObjectName("board_combo")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.board_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.board_combo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.general_tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.mount_combo = QtWidgets.QComboBox(self.general_tab)
        self.mount_combo.setObjectName("mount_combo")
        self.mount_combo.addItem("")
        self.mount_combo.addItem("")
        self.mount_combo.addItem("")
        self.horizontalLayout.addWidget(self.mount_combo)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.general_tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.maxrate_spin = QtWidgets.QSpinBox(self.general_tab)
        self.maxrate_spin.setMaximum(256)
        self.maxrate_spin.setProperty("value", 96)
        self.maxrate_spin.setObjectName("maxrate_spin")
        self.horizontalLayout_3.addWidget(self.maxrate_spin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.general_tab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.comboBox_11 = QtWidgets.QComboBox(self.general_tab)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.axis2_mod_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis2_mod_combo.setObjectName("axis2_mod_combo")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.axis2_mod_combo.addItem("")
        self.gridLayout.addWidget(self.axis2_mod_combo, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.general_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.axis1_mod_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis1_mod_combo.setObjectName("axis1_mod_combo")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.axis1_mod_combo.addItem("")
        self.gridLayout.addWidget(self.axis1_mod_combo, 5, 1, 1, 1)
        self.axis2_motor_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis2_motor_combo.setObjectName("axis2_motor_combo")
        self.axis2_motor_combo.addItem("")
        self.axis2_motor_combo.addItem("")
        self.axis2_motor_combo.addItem("")
        self.gridLayout.addWidget(self.axis2_motor_combo, 3, 2, 1, 1)
        self.axis1_driver_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis1_driver_combo.setObjectName("axis1_driver_combo")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.axis1_driver_combo.addItem("")
        self.gridLayout.addWidget(self.axis1_driver_combo, 6, 1, 1, 1)
        self.axis1_gear_spindouble = QtWidgets.QDoubleSpinBox(self.general_tab)
        self.axis1_gear_spindouble.setDecimals(3)
        self.axis1_gear_spindouble.setMinimum(1.0)
        self.axis1_gear_spindouble.setMaximum(99999.99)
        self.axis1_gear_spindouble.setObjectName("axis1_gear_spindouble")
        self.gridLayout.addWidget(self.axis1_gear_spindouble, 2, 1, 1, 1)
        self.axis1_worm_spindouble = QtWidgets.QDoubleSpinBox(self.general_tab)
        self.axis1_worm_spindouble.setDecimals(3)
        self.axis1_worm_spindouble.setMinimum(1.0)
        self.axis1_worm_spindouble.setMaximum(99999.99)
        self.axis1_worm_spindouble.setProperty("value", 144.0)
        self.axis1_worm_spindouble.setObjectName("axis1_worm_spindouble")
        self.gridLayout.addWidget(self.axis1_worm_spindouble, 1, 1, 1, 1)
        self.axis2_driver_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis2_driver_combo.setObjectName("axis2_driver_combo")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.axis2_driver_combo.addItem("")
        self.gridLayout.addWidget(self.axis2_driver_combo, 6, 2, 1, 1)
        self.axis2_worm_spindouble = QtWidgets.QDoubleSpinBox(self.general_tab)
        self.axis2_worm_spindouble.setDecimals(3)
        self.axis2_worm_spindouble.setMinimum(1.0)
        self.axis2_worm_spindouble.setMaximum(99999.99)
        self.axis2_worm_spindouble.setProperty("value", 144.0)
        self.axis2_worm_spindouble.setObjectName("axis2_worm_spindouble")
        self.gridLayout.addWidget(self.axis2_worm_spindouble, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.general_tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.general_tab)
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout.addWidget(self.checkBox_20, 7, 1, 1, 1)
        self.axis2_gear_spindouble = QtWidgets.QDoubleSpinBox(self.general_tab)
        self.axis2_gear_spindouble.setDecimals(3)
        self.axis2_gear_spindouble.setMinimum(1.0)
        self.axis2_gear_spindouble.setMaximum(99999.99)
        self.axis2_gear_spindouble.setProperty("value", 1.0)
        self.axis2_gear_spindouble.setObjectName("axis2_gear_spindouble")
        self.gridLayout.addWidget(self.axis2_gear_spindouble, 2, 2, 1, 1)
        self.axis1_motor_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis1_motor_combo.setObjectName("axis1_motor_combo")
        self.axis1_motor_combo.addItem("")
        self.axis1_motor_combo.addItem("")
        self.axis1_motor_combo.addItem("")
        self.gridLayout.addWidget(self.axis1_motor_combo, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.general_tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.axis2_micro_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis2_micro_combo.setObjectName("axis2_micro_combo")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.axis2_micro_combo.addItem("")
        self.gridLayout.addWidget(self.axis2_micro_combo, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.general_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.axis1_micro_combo = QtWidgets.QComboBox(self.general_tab)
        self.axis1_micro_combo.setObjectName("axis1_micro_combo")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.axis1_micro_combo.addItem("")
        self.gridLayout.addWidget(self.axis1_micro_combo, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.general_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.general_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.general_tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.general_tab)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 7, 0, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.general_tab)
        self.checkBox_21.setText("")
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout.addWidget(self.checkBox_21, 7, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.general_tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.general_tab)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 8, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.general_tab)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 8, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.general_tab)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 8, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.general_tab)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 9, 0, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.general_tab)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout.addWidget(self.comboBox_6, 9, 1, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.general_tab)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout.addWidget(self.comboBox_7, 9, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.general_tab, "")
        self.axis3_2_tab = QtWidgets.QWidget()
        self.axis3_2_tab.setObjectName("axis3_2_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.axis3_2_tab)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_35 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 8, 0, 1, 1)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.doubleSpinBox_10.setEnabled(False)
        self.doubleSpinBox_10.setMinimum(-180.0)
        self.doubleSpinBox_10.setMaximum(180.0)
        self.doubleSpinBox_10.setProperty("value", 180.0)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.gridLayout_3.addWidget(self.doubleSpinBox_10, 8, 1, 1, 1)
        self.spinBox_12 = QtWidgets.QSpinBox(self.axis3_2_tab)
        self.spinBox_12.setEnabled(False)
        self.spinBox_12.setMaximum(256)
        self.spinBox_12.setProperty("value", 8)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout_3.addWidget(self.spinBox_12, 1, 1, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.doubleSpinBox_5.setEnabled(False)
        self.doubleSpinBox_5.setMinimum(-999999.99)
        self.doubleSpinBox_5.setMaximum(999999.99)
        self.doubleSpinBox_5.setProperty("value", -25.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_3.addWidget(self.doubleSpinBox_5, 7, 2, 1, 1)
        self.spinBox_14 = QtWidgets.QSpinBox(self.axis3_2_tab)
        self.spinBox_14.setEnabled(False)
        self.spinBox_14.setMaximum(256)
        self.spinBox_14.setProperty("value", 8)
        self.spinBox_14.setObjectName("spinBox_14")
        self.gridLayout_3.addWidget(self.spinBox_14, 1, 3, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 4, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_37 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_7.addWidget(self.label_37)
        self.label_42 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_7.addWidget(self.label_42)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 5, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 6, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_40.setObjectName("label_40")
        self.gridLayout_3.addWidget(self.label_40, 7, 0, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.doubleSpinBox_7.setEnabled(False)
        self.doubleSpinBox_7.setMaximum(999999.99)
        self.doubleSpinBox_7.setProperty("value", 0.5)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_3.addWidget(self.doubleSpinBox_7, 5, 2, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.axis3_2_tab)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_3.addWidget(self.checkBox_25, 0, 3, 1, 1)
        self.checkBox_26 = QtWidgets.QCheckBox(self.axis3_2_tab)
        self.checkBox_26.setEnabled(False)
        self.checkBox_26.setText("")
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_3.addWidget(self.checkBox_26, 6, 1, 1, 1)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.doubleSpinBox_12.setEnabled(False)
        self.doubleSpinBox_12.setMinimum(-999999.0)
        self.doubleSpinBox_12.setMaximum(999999.99)
        self.doubleSpinBox_12.setProperty("value", 25.0)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.gridLayout_3.addWidget(self.doubleSpinBox_12, 8, 3, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.axis3_2_tab)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_3.addWidget(self.checkBox_24, 0, 2, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.axis3_2_tab)
        self.comboBox_8.setEnabled(False)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_3.addWidget(self.comboBox_8, 2, 1, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.axis3_2_tab)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_3.addWidget(self.checkBox_23, 0, 1, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(self.axis3_2_tab)
        self.checkBox_28.setEnabled(False)
        self.checkBox_28.setText("")
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout_3.addWidget(self.checkBox_28, 6, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 1, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.axis3_2_tab)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 3, 0, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.doubleSpinBox_8.setEnabled(False)
        self.doubleSpinBox_8.setMaximum(999999.99)
        self.doubleSpinBox_8.setProperty("value", 0.5)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_3.addWidget(self.doubleSpinBox_8, 5, 3, 1, 1)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.doubleSpinBox_11.setEnabled(False)
        self.doubleSpinBox_11.setMinimum(-999999.99)
        self.doubleSpinBox_11.setMaximum(999999.99)
        self.doubleSpinBox_11.setProperty("value", 25.0)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.gridLayout_3.addWidget(self.doubleSpinBox_11, 8, 2, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.doubleSpinBox_4.setEnabled(False)
        self.doubleSpinBox_4.setMinimum(-180.0)
        self.doubleSpinBox_4.setMaximum(180.0)
        self.doubleSpinBox_4.setProperty("value", -180.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_3.addWidget(self.doubleSpinBox_4, 7, 1, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.doubleSpinBox_3.setEnabled(False)
        self.doubleSpinBox_3.setMaximum(999999.99)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_3.addWidget(self.doubleSpinBox_3, 5, 1, 1, 1)
        self.spinBox_13 = QtWidgets.QSpinBox(self.axis3_2_tab)
        self.spinBox_13.setEnabled(False)
        self.spinBox_13.setMaximum(256)
        self.spinBox_13.setProperty("value", 8)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridLayout_3.addWidget(self.spinBox_13, 1, 2, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.axis3_2_tab)
        self.checkBox_27.setEnabled(False)
        self.checkBox_27.setText("")
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_3.addWidget(self.checkBox_27, 6, 2, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.axis3_2_tab)
        self.comboBox_12.setEnabled(False)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_12, 3, 1, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.doubleSpinBox_9.setEnabled(False)
        self.doubleSpinBox_9.setMinimum(-999999.99)
        self.doubleSpinBox_9.setMaximum(999999.99)
        self.doubleSpinBox_9.setProperty("value", -25.0)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout_3.addWidget(self.doubleSpinBox_9, 7, 3, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.axis3_2_tab)
        self.doubleSpinBox_6.setEnabled(False)
        self.doubleSpinBox_6.setMaximum(999999.99)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_3.addWidget(self.doubleSpinBox_6, 4, 1, 1, 1)
        self.tabWidget.addTab(self.axis3_2_tab, "")
        self.option_tab = QtWidgets.QWidget()
        self.option_tab.setObjectName("option_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.option_tab)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(self.option_tab)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 742, 857))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        self.comboBox_3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_4.addWidget(self.checkBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setEnabled(False)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.pec_spin = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.pec_spin.setEnabled(False)
        self.pec_spin.setMaximum(100000)
        self.pec_spin.setProperty("value", 824)
        self.pec_spin.setObjectName("pec_spin")
        self.horizontalLayout_4.addWidget(self.pec_spin)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_8.addWidget(self.checkBox_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_8.addWidget(self.checkBox_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_8.addWidget(self.checkBox_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.checkBox_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_3.addWidget(self.checkBox_7)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.spinBox_4 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox_4.setMaximum(86400)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout_14.addWidget(self.spinBox_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_14 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout_9.addWidget(self.checkBox_14)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox.setEnabled(False)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.checkBox_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_3.addWidget(self.checkBox_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_10.addWidget(self.checkBox_9)
        self.spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox.setEnabled(False)
        self.spinBox.setMaximum(1023)
        self.spinBox.setProperty("value", 1023)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_10.addWidget(self.spinBox)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.checkBox_10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout_3.addWidget(self.checkBox_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_11.addWidget(self.checkBox_11)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.checkBox_13 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_13.setEnabled(False)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_11.addWidget(self.checkBox_13)
        self.spinBox_2 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox_2.setEnabled(False)
        self.spinBox_2.setMaximum(255)
        self.spinBox_2.setProperty("value", 255)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_11.addWidget(self.spinBox_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout_3.addWidget(self.checkBox_12)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_15 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_15.setObjectName("checkBox_15")
        self.horizontalLayout_12.addWidget(self.checkBox_15)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setEnabled(False)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.spinBox_3 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox_3.setEnabled(False)
        self.spinBox_3.setMaximum(30000)
        self.spinBox_3.setProperty("value", 2000)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_12.addWidget(self.spinBox_3)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.checkBox_16 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_16.setEnabled(False)
        self.checkBox_16.setChecked(True)
        self.checkBox_16.setObjectName("checkBox_16")
        self.horizontalLayout_12.addWidget(self.checkBox_16)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.checkBox_17 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_17.setObjectName("checkBox_17")
        self.verticalLayout_3.addWidget(self.checkBox_17)
        self.checkBox_18 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_18.setObjectName("checkBox_18")
        self.verticalLayout_3.addWidget(self.checkBox_18)
        self.checkBox_19 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_19.setObjectName("checkBox_19")
        self.verticalLayout_3.addWidget(self.checkBox_19)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_17.addWidget(self.label_22)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setMinimum(1.0)
        self.doubleSpinBox_2.setSingleStep(1.0)
        self.doubleSpinBox_2.setProperty("value", 5.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_17.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_16.addWidget(self.label_23)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents_2)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMinimum(1.0)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_16.addWidget(self.doubleSpinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_15.addWidget(self.label_24)
        self.spinBox_5 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox_5.setProperty("value", 25)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_15.addWidget(self.spinBox_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.checkBox_22 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_22.setObjectName("checkBox_22")
        self.verticalLayout_3.addWidget(self.checkBox_22)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_18.addWidget(self.label_28)
        self.spinBox_6 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox_6.setMinimum(-360)
        self.spinBox_6.setMaximum(360)
        self.spinBox_6.setProperty("value", 30)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_18.addWidget(self.spinBox_6)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_18.addWidget(self.label_29)
        self.spinBox_7 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox_7.setMinimum(-360)
        self.spinBox_7.setMaximum(360)
        self.spinBox_7.setProperty("value", 30)
        self.spinBox_7.setObjectName("spinBox_7")
        self.horizontalLayout_18.addWidget(self.spinBox_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_19.addWidget(self.label_30)
        self.spinBox_8 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox_8.setMinimum(-91)
        self.spinBox_8.setMaximum(90)
        self.spinBox_8.setProperty("value", -91)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_19.addWidget(self.spinBox_8)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_19.addWidget(self.label_31)
        self.spinBox_9 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox_9.setMinimum(-91)
        self.spinBox_9.setMaximum(91)
        self.spinBox_9.setProperty("value", 91)
        self.spinBox_9.setObjectName("spinBox_9")
        self.horizontalLayout_19.addWidget(self.spinBox_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_20.addWidget(self.label_32)
        self.spinBox_10 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox_10.setMinimum(10)
        self.spinBox_10.setMaximum(12)
        self.spinBox_10.setProperty("value", 12)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_20.addWidget(self.spinBox_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_21.addWidget(self.label_33)
        self.spinBox_11 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spinBox_11.setMinimum(180)
        self.spinBox_11.setMaximum(360)
        self.spinBox_11.setProperty("value", 180)
        self.spinBox_11.setObjectName("spinBox_11")
        self.horizontalLayout_21.addWidget(self.spinBox_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.option_tab, "")
        self.arduino_tab = QtWidgets.QWidget()
        self.arduino_tab.setObjectName("arduino_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.arduino_tab)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_17 = QtWidgets.QLabel(self.arduino_tab)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.arduino_tab)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.arduino_tab)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.arduino_tab)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_10.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.arduino_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.generate_buttom = QtWidgets.QPushButton(self.centralWidget)
        self.generate_buttom.setObjectName("generate_buttom")
        self.verticalLayout.addWidget(self.generate_buttom)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.path_line = QtWidgets.QLineEdit(self.centralWidget)
        self.path_line.setObjectName("path_line")
        self.horizontalLayout_6.addWidget(self.path_line)
        self.path_button = QtWidgets.QToolButton(self.centralWidget)
        self.path_button.setObjectName("path_button")
        self.horizontalLayout_6.addWidget(self.path_button)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.prompt_textbrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.prompt_textbrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.prompt_textbrowser.setObjectName("prompt_textbrowser")
        self.verticalLayout.addWidget(self.prompt_textbrowser)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        configurator.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(configurator)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuOnStep_Configurator = QtWidgets.QMenu(self.menuBar)
        self.menuOnStep_Configurator.setObjectName("menuOnStep_Configurator")
        self.menuInfo = QtWidgets.QMenu(self.menuBar)
        self.menuInfo.setObjectName("menuInfo")
        configurator.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(configurator)
        self.actionSave.setCheckable(False)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(configurator)
        self.actionLoad.setCheckable(False)
        self.actionLoad.setObjectName("actionLoad")
        self.actionAbout = QtWidgets.QAction(configurator)
        self.actionAbout.setCheckable(False)
        self.actionAbout.setEnabled(True)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOnStep_Configurator.addAction(self.actionSave)
        self.menuOnStep_Configurator.addAction(self.actionLoad)
        self.menuInfo.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuOnStep_Configurator.menuAction())
        self.menuBar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(configurator)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(10)
        self.buttonBox.clicked['QAbstractButton*'].connect(configurator.close)
        self.checkBox_14.clicked['bool'].connect(self.checkBox_12.setDisabled)
        self.checkBox.clicked['bool'].connect(self.pec_spin.setEnabled)
        self.checkBox_5.clicked['bool'].connect(self.checkBox_6.setEnabled)
        self.checkBox_5.clicked['bool'].connect(self.checkBox_4.setEnabled)
        self.checkBox_9.clicked['bool'].connect(self.spinBox.setEnabled)
        self.checkBox_9.clicked['bool'].connect(self.comboBox_2.setEnabled)
        self.checkBox_11.clicked['bool'].connect(self.checkBox_13.setEnabled)
        self.checkBox_13.clicked['bool'].connect(self.spinBox_2.setEnabled)
        self.checkBox_14.clicked['bool'].connect(self.comboBox.setEnabled)
        self.checkBox_12.clicked['bool'].connect(self.checkBox_14.setDisabled)
        self.checkBox.clicked['bool'].connect(self.label_9.setEnabled)
        self.checkBox_15.clicked['bool'].connect(self.label_19.setEnabled)
        self.checkBox_15.clicked['bool'].connect(self.spinBox_3.setEnabled)
        self.checkBox_15.clicked['bool'].connect(self.checkBox_16.setEnabled)
        self.checkBox_23.clicked['bool'].connect(self.spinBox_12.setEnabled)
        self.checkBox_23.clicked['bool'].connect(self.comboBox_8.setEnabled)
        self.checkBox_23.clicked['bool'].connect(self.comboBox_12.setEnabled)
        self.checkBox_23.clicked['bool'].connect(self.doubleSpinBox_3.setEnabled)
        self.checkBox_23.clicked['bool'].connect(self.doubleSpinBox_6.setEnabled)
        self.checkBox_23.clicked['bool'].connect(self.checkBox_26.setEnabled)
        self.checkBox_23.clicked['bool'].connect(self.doubleSpinBox_4.setEnabled)
        self.checkBox_23.clicked['bool'].connect(self.doubleSpinBox_10.setEnabled)
        self.checkBox_24.clicked['bool'].connect(self.spinBox_13.setEnabled)
        self.checkBox_24.clicked['bool'].connect(self.doubleSpinBox_7.setEnabled)
        self.checkBox_24.clicked['bool'].connect(self.checkBox_27.setEnabled)
        self.checkBox_24.clicked['bool'].connect(self.doubleSpinBox_5.setEnabled)
        self.checkBox_24.clicked['bool'].connect(self.doubleSpinBox_11.setEnabled)
        self.checkBox_25.clicked['bool'].connect(self.spinBox_14.setEnabled)
        self.checkBox_25.clicked['bool'].connect(self.doubleSpinBox_8.setEnabled)
        self.checkBox_25.clicked['bool'].connect(self.checkBox_28.setEnabled)
        self.checkBox_25.clicked['bool'].connect(self.doubleSpinBox_9.setEnabled)
        self.checkBox_25.clicked['bool'].connect(self.doubleSpinBox_12.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(configurator)

    def retranslateUi(self, configurator):
        _translate = QtCore.QCoreApplication.translate
        configurator.setWindowTitle(_translate("configurator", "configurator"))
        self.label_14.setText(_translate("configurator", "Configuration Parameters"))
        self.label_8.setText(_translate("configurator", "Board Type"))
        self.board_combo.setItemText(0, _translate("configurator", "RAMPS 1.4 or 1.5"))
        self.board_combo.setItemText(1, _translate("configurator", "MiniPCB (2 axis)"))
        self.board_combo.setItemText(2, _translate("configurator", "MaxPCB (4 axis)"))
        self.board_combo.setItemText(3, _translate("configurator", "STM32F1"))
        self.board_combo.setItemText(4, _translate("configurator", "TivaC"))
        self.board_combo.setItemText(5, _translate("configurator", "Classic"))
        self.board_combo.setItemText(6, _translate("configurator", "Mega2560 Alternate"))
        self.board_combo.setItemText(7, _translate("configurator", "Custom"))
        self.label_7.setText(_translate("configurator", "Mount Type"))
        self.mount_combo.setItemText(0, _translate("configurator", "Equatorial"))
        self.mount_combo.setItemText(1, _translate("configurator", "Alt-Azimuth"))
        self.mount_combo.setItemText(2, _translate("configurator", "Fork"))
        self.label_10.setText(_translate("configurator", "Max Rate Ratio"))
        self.label_13.setText(_translate("configurator", "Auto Sideral Traking mod"))
        self.comboBox_11.setItemText(0, _translate("configurator", "OFF"))
        self.comboBox_11.setItemText(1, _translate("configurator", "ON"))
        self.axis2_mod_combo.setItemText(0, _translate("configurator", "OFF"))
        self.axis2_mod_combo.setItemText(1, _translate("configurator", "1"))
        self.axis2_mod_combo.setItemText(2, _translate("configurator", "2"))
        self.axis2_mod_combo.setItemText(3, _translate("configurator", "4"))
        self.axis2_mod_combo.setItemText(4, _translate("configurator", "8"))
        self.axis2_mod_combo.setItemText(5, _translate("configurator", "16"))
        self.axis2_mod_combo.setItemText(6, _translate("configurator", "32"))
        self.axis2_mod_combo.setItemText(7, _translate("configurator", "64"))
        self.axis2_mod_combo.setItemText(8, _translate("configurator", "128"))
        self.axis2_mod_combo.setItemText(9, _translate("configurator", "256"))
        self.label_3.setText(_translate("configurator", "Worm Wheel Ratio"))
        self.axis1_mod_combo.setItemText(0, _translate("configurator", "OFF"))
        self.axis1_mod_combo.setItemText(1, _translate("configurator", "1"))
        self.axis1_mod_combo.setItemText(2, _translate("configurator", "2"))
        self.axis1_mod_combo.setItemText(3, _translate("configurator", "4"))
        self.axis1_mod_combo.setItemText(4, _translate("configurator", "8"))
        self.axis1_mod_combo.setItemText(5, _translate("configurator", "16"))
        self.axis1_mod_combo.setItemText(6, _translate("configurator", "32"))
        self.axis1_mod_combo.setItemText(7, _translate("configurator", "64"))
        self.axis1_mod_combo.setItemText(8, _translate("configurator", "128"))
        self.axis1_mod_combo.setItemText(9, _translate("configurator", "256"))
        self.axis2_motor_combo.setItemText(0, _translate("configurator", "200 steps, 1.8°/step"))
        self.axis2_motor_combo.setItemText(1, _translate("configurator", "400 steps, 0.9°/step"))
        self.axis2_motor_combo.setItemText(2, _translate("configurator", "48 steps, 7.5°/step"))
        self.axis1_driver_combo.setItemText(0, _translate("configurator", "A4988"))
        self.axis1_driver_combo.setItemText(1, _translate("configurator", "DRV8825"))
        self.axis1_driver_combo.setItemText(2, _translate("configurator", "LV8729 or RAPS128"))
        self.axis1_driver_combo.setItemText(3, _translate("configurator", "TMC2208"))
        self.axis1_driver_combo.setItemText(4, _translate("configurator", "TMC2130"))
        self.axis1_driver_combo.setItemText(5, _translate("configurator", "TMC2130 (Quiet)"))
        self.axis1_driver_combo.setItemText(6, _translate("configurator", "TMC2130 (VQuiet)"))
        self.axis1_driver_combo.setItemText(7, _translate("configurator", "TMC2130 (Quiet, LowPWR)"))
        self.axis1_driver_combo.setItemText(8, _translate("configurator", "TMC2130 (VQuiet, LowPWR)"))
        self.axis2_driver_combo.setItemText(0, _translate("configurator", "A4988"))
        self.axis2_driver_combo.setItemText(1, _translate("configurator", "DRV8825"))
        self.axis2_driver_combo.setItemText(2, _translate("configurator", "LV8729 or RAPS128"))
        self.axis2_driver_combo.setItemText(3, _translate("configurator", "TMC2208"))
        self.axis2_driver_combo.setItemText(4, _translate("configurator", "TMC2130"))
        self.axis2_driver_combo.setItemText(5, _translate("configurator", "TMC2130 (Quiet)"))
        self.axis2_driver_combo.setItemText(6, _translate("configurator", "TMC2130 (VQuiet)"))
        self.axis2_driver_combo.setItemText(7, _translate("configurator", "TMC2130 (Quiet, LowPWR)"))
        self.axis2_driver_combo.setItemText(8, _translate("configurator", "TMC2130 (VQuiet, LowPWR)"))
        self.label_4.setText(_translate("configurator", "Gears/Pulleys Ratio"))
        self.axis1_motor_combo.setItemText(0, _translate("configurator", "200 steps, 1.8°/step"))
        self.axis1_motor_combo.setItemText(1, _translate("configurator", "400 steps, 1.8°/step"))
        self.axis1_motor_combo.setItemText(2, _translate("configurator", "48 steps, 7.5°/step"))
        self.label.setText(_translate("configurator", "Axis 1"))
        self.axis2_micro_combo.setItemText(0, _translate("configurator", "1"))
        self.axis2_micro_combo.setItemText(1, _translate("configurator", "2"))
        self.axis2_micro_combo.setItemText(2, _translate("configurator", "4"))
        self.axis2_micro_combo.setItemText(3, _translate("configurator", "8"))
        self.axis2_micro_combo.setItemText(4, _translate("configurator", "16"))
        self.axis2_micro_combo.setItemText(5, _translate("configurator", "32"))
        self.axis2_micro_combo.setItemText(6, _translate("configurator", "64"))
        self.axis2_micro_combo.setItemText(7, _translate("configurator", "128"))
        self.axis2_micro_combo.setItemText(8, _translate("configurator", "256"))
        self.label_5.setText(_translate("configurator", "Stepper-Steps"))
        self.axis1_micro_combo.setItemText(0, _translate("configurator", "1"))
        self.axis1_micro_combo.setItemText(1, _translate("configurator", "2"))
        self.axis1_micro_combo.setItemText(2, _translate("configurator", "4"))
        self.axis1_micro_combo.setItemText(3, _translate("configurator", "8"))
        self.axis1_micro_combo.setItemText(4, _translate("configurator", "16"))
        self.axis1_micro_combo.setItemText(5, _translate("configurator", "32"))
        self.axis1_micro_combo.setItemText(6, _translate("configurator", "64"))
        self.axis1_micro_combo.setItemText(7, _translate("configurator", "128"))
        self.axis1_micro_combo.setItemText(8, _translate("configurator", "256"))
        self.label_6.setText(_translate("configurator", "MicroSteps Tracking"))
        self.label_2.setText(_translate("configurator", "Axis 2"))
        self.label_11.setText(_translate("configurator", "MicroSteps Slewing"))
        self.label_25.setText(_translate("configurator", "Reverse axis"))
        self.label_12.setText(_translate("configurator", "Driver Model"))
        self.comboBox_4.setItemText(0, _translate("configurator", "HIGH"))
        self.comboBox_4.setItemText(1, _translate("configurator", "LOW"))
        self.comboBox_5.setItemText(0, _translate("configurator", "HIGH"))
        self.comboBox_5.setItemText(1, _translate("configurator", "LOW"))
        self.label_26.setText(_translate("configurator", "Enable support"))
        self.label_27.setText(_translate("configurator", "Fault Detection "))
        self.comboBox_6.setItemText(0, _translate("configurator", "OFF"))
        self.comboBox_6.setItemText(1, _translate("configurator", "HIGH"))
        self.comboBox_6.setItemText(2, _translate("configurator", "LOW"))
        self.comboBox_7.setItemText(0, _translate("configurator", "OFF"))
        self.comboBox_7.setItemText(1, _translate("configurator", "HIGH"))
        self.comboBox_7.setItemText(2, _translate("configurator", "LOW"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general_tab), _translate("configurator", "General"))
        self.label_35.setText(_translate("configurator", " Stepper Steps"))
        self.label_41.setText(_translate("configurator", " Max axis (degrees or millimeters)"))
        self.label_38.setText(_translate("configurator", " Gear 1 reduction Ratio"))
        self.label_37.setText(_translate("configurator", " Rotator : Gear 2 reduction Ratio"))
        self.label_42.setText(_translate("configurator", " Focuser : Step/MicroMeter"))
        self.label_39.setText(_translate("configurator", " Reverse Axis"))
        self.label_40.setText(_translate("configurator", " Min axis (degrees or millimeters)"))
        self.checkBox_25.setText(_translate("configurator", "Focuser 2"))
        self.checkBox_24.setText(_translate("configurator", "Focuser 1"))
        self.checkBox_23.setText(_translate("configurator", "De-Rotator"))
        self.label_34.setText(_translate("configurator", " Max Rate Ratio"))
        self.label_36.setText(_translate("configurator", " Micro Steps"))
        self.comboBox_12.setItemText(0, _translate("configurator", "1"))
        self.comboBox_12.setItemText(1, _translate("configurator", "2"))
        self.comboBox_12.setItemText(2, _translate("configurator", "4"))
        self.comboBox_12.setItemText(3, _translate("configurator", "8"))
        self.comboBox_12.setItemText(4, _translate("configurator", "16"))
        self.comboBox_12.setItemText(5, _translate("configurator", "32"))
        self.comboBox_12.setItemText(6, _translate("configurator", "64"))
        self.comboBox_12.setItemText(7, _translate("configurator", "128"))
        self.comboBox_12.setItemText(8, _translate("configurator", "256"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.axis3_2_tab), _translate("configurator", "Axis3/2"))
        self.label_18.setText(_translate("configurator", "Tick for activate option :"))
        self.label_20.setText(_translate("configurator", "Serial 1 Baud (bit/s):"))
        self.comboBox_3.setItemText(0, _translate("configurator", "75"))
        self.comboBox_3.setItemText(1, _translate("configurator", "110"))
        self.comboBox_3.setItemText(2, _translate("configurator", "134.5"))
        self.comboBox_3.setItemText(3, _translate("configurator", "150"))
        self.comboBox_3.setItemText(4, _translate("configurator", "600"))
        self.comboBox_3.setItemText(5, _translate("configurator", "1200"))
        self.comboBox_3.setItemText(6, _translate("configurator", "1800"))
        self.comboBox_3.setItemText(7, _translate("configurator", "2400"))
        self.comboBox_3.setItemText(8, _translate("configurator", "4800"))
        self.comboBox_3.setItemText(9, _translate("configurator", "7200"))
        self.comboBox_3.setItemText(10, _translate("configurator", "9600"))
        self.comboBox_3.setItemText(11, _translate("configurator", "14400"))
        self.comboBox_3.setItemText(12, _translate("configurator", "19200"))
        self.comboBox_3.setItemText(13, _translate("configurator", "38400"))
        self.comboBox_3.setItemText(14, _translate("configurator", "56000"))
        self.comboBox_3.setItemText(15, _translate("configurator", "57600"))
        self.comboBox_3.setItemText(16, _translate("configurator", "115200"))
        self.comboBox_3.setItemText(17, _translate("configurator", "128000"))
        self.checkBox.setText(_translate("configurator", "PEC"))
        self.label_9.setText(_translate("configurator", "PEC Buffer Size :"))
        self.checkBox_2.setText(_translate("configurator", "Align Goto Assist"))
        self.checkBox_3.setText(_translate("configurator", "Strict Parking"))
        self.checkBox_5.setText(_translate("configurator", "ST4"))
        self.checkBox_6.setText(_translate("configurator", "Alternate Pins"))
        self.checkBox_4.setText(_translate("configurator", "Hand Control"))
        self.checkBox_7.setText(_translate("configurator", "Separate pulse guide rate"))
        self.label_21.setText(_translate("configurator", "Guide time Limit (seconds) :"))
        self.checkBox_14.setText(_translate("configurator", "RTC"))
        self.comboBox.setItemText(0, _translate("configurator", "RTC_DS3234"))
        self.checkBox_8.setText(_translate("configurator", "PPS sensor"))
        self.checkBox_9.setText(_translate("configurator", "PEC sensor ( 0 for digital)"))
        self.comboBox_2.setItemText(0, _translate("configurator", "HIGH"))
        self.comboBox_2.setItemText(1, _translate("configurator", "LOW"))
        self.checkBox_10.setText(_translate("configurator", "Limit Sensor"))
        self.checkBox_11.setText(_translate("configurator", "Status LED"))
        self.checkBox_13.setText(_translate("configurator", "Reticule LED"))
        self.checkBox_12.setText(_translate("configurator", "Status LED 2"))
        self.checkBox_15.setText(_translate("configurator", "Buzzer"))
        self.label_19.setText(_translate("configurator", "Buzzer frequency (Hz) :"))
        self.checkBox_16.setText(_translate("configurator", "Default Sound"))
        self.checkBox_17.setText(_translate("configurator", "Traking compensation for atmospheric refaction"))
        self.checkBox_18.setText(_translate("configurator", "Home Pause"))
        self.checkBox_19.setText(_translate("configurator", "Remember Max Rate"))
        self.label_22.setText(_translate("configurator", "Degrees for Acceleration :"))
        self.label_23.setText(_translate("configurator", "Degrees for Rapid Stop :"))
        self.label_24.setText(_translate("configurator", "Backlash Take up Rate :"))
        self.checkBox_22.setText(_translate("configurator", "Auto Power Off Axis 2"))
        self.label_28.setText(_translate("configurator", "Minute Past Meridian E"))
        self.label_29.setText(_translate("configurator", "W"))
        self.label_30.setText(_translate("configurator", "Minimum DEC"))
        self.label_31.setText(_translate("configurator", "Maximum DEC"))
        self.label_32.setText(_translate("configurator", "Under Pole Limit (hours)"))
        self.label_33.setText(_translate("configurator", "Max Azimuth (degrees)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.option_tab), _translate("configurator", "Option"))
        self.label_17.setText(_translate("configurator", "This Tab is dedicated to generate and upload the OnStep code in the board"))
        self.label_16.setText(_translate("configurator", "Coming Soon !!!"))
        self.pushButton_2.setText(_translate("configurator", "Build"))
        self.pushButton.setText(_translate("configurator", "Upload"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.arduino_tab), _translate("configurator", "Compile and Upload"))
        self.generate_buttom.setText(_translate("configurator", "Generate"))
        self.path_button.setText(_translate("configurator", "..."))
        self.prompt_textbrowser.setHtml(_translate("configurator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Configure your setup for Onstep !</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Standby...</p></body></html>"))
        self.menuOnStep_Configurator.setTitle(_translate("configurator", "File"))
        self.menuInfo.setTitle(_translate("configurator", "Info"))
        self.actionSave.setText(_translate("configurator", "Save"))
        self.actionSave.setShortcut(_translate("configurator", "Ctrl+S"))
        self.actionLoad.setText(_translate("configurator", "Load"))
        self.actionLoad.setShortcut(_translate("configurator", "Ctrl+O"))
        self.actionAbout.setText(_translate("configurator", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    configurator = QtWidgets.QMainWindow()
    ui = Ui_configurator()
    ui.setupUi(configurator)
    configurator.show()
    sys.exit(app.exec_())

